// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jnovfwhvqjwmkhnvuwsr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impub3Zmd2h2cWp3bWtobnZ1d3NyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMjEwMzAsImV4cCI6MjA2MjY5NzAzMH0.DEhnaBPaoKYgyTp_MGw6sDF1_LVSegs0kItvE_4RPUE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);